import Head from "next/head";
import Image from "next/image";
import SignIn from "./signin";

export default function Home() {
  return (
    <>
      <Head>
        <title>핑크구조대</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignIn/>
    </>
  );
}
